name: CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  vuln-image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Build the Container image
        working-directory: .
        run: docker build . --file Dockerfile --tag portfolio:latest
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: portfolio:latest
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'